name: CrossFoundation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: CrossFoundation-${{ github.head_ref }}
  cancel-in-progress: true

env:
    MISE_EXPERIMENTAL: "1"
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        os: [ubuntu-latest, macos-15, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: jdx/mise-action@v2
      - uses: swift-actions/setup-swift@v2
        with:
            swift-version: "6.0.2"
    #   - if: runner.os == 'macOS'
    #     run: sudo xcode-select -s /Applications/Xcode_16.2.app
      - if: runner.os == 'Linux' || runner.os == 'macOS'
        run: mise run test:package
      - if: runner.os == 'Windows'
        run: |
          zig build -Dtarget="x86_64-windows" -Doptimize=ReleaseSmall
          New-Item -ItemType Directory -Force -Path "Sources/CrossFoundation/Native/x86_64-windows/lib"
          New-Item -ItemType Directory -Force -Path "Sources/CrossFoundation/Native/x86_64-windows/include"
          Copy-Item -Force -Path "zig-out/lib/CrossFoundation.lib" -Destination "Sources/CrossFoundation/Native/x86_64-windows/lib/Cross.lib"
          Copy-Item -Force -Path "include/Cross.h" -Destination "Sources/CrossFoundation/Native/x86_64-windows/include/Cross.h"
          Copy-Item -Force -Path "include/module.modulemap" -Destination "Sources/CrossFoundation/Native/x86_64-windows/include/module.modulemap"
