name: Cross Foundation CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
    MISE_EXPERIMENTAL: "1"
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: jdx/mise-action@v2
      - run: mise run test:package
