name: CrossFoundation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
    MISE_EXPERIMENTAL: "1"
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: jdx/mise-action@v2
      - if: runner.os == 'Linux' || runner.os == 'Windows'
        run: swift --version
      - if: runner.os == 'Linux' || runner.os == 'macOS'
        run: mise run test:package
